### PR TITLE
added root solutions logo

### PR DESCRIPTION
**Pull request by oliver-vergara**
ready to merge. please test

### CODE REVIEW

**Comment by ohkwon** [comment]
Titles for following sections of the parallax is vertically mis-aligned. please fix

**Comment by oliver-vergara** [comment]
This card is just for logo and not the titles

**Comment by markeban** [comment]
@oliver-vergara But your changes have inadvertently changed the titles below it. You'll need to fix those before we'll merge.

**Comment by oliver-vergara** [comment]
ok

**Comment by oliver-vergara** [comment]
I already fixed it. I didn't notice it changed because I was only focused on the main title. I had to remove position: absolute; because it was messing with the alignment of the logo and the root solutions title. But everything should be alright now. please check the new commit.

**Comment by ohkwon** [comment]
thanks for fixing it, looks good

**Pull request merged**
