### PR TITLE
Uiissues

### PR DESCRIPTION
**Pull request by Marisha-Sahay**
Fixed the careers page as per the comment, i.e, title of image below the image rather than on right of the image.
Changed the learn page and added parallax design for the same.

### CODE REVIEW

**Comment by ohkwon** [comment]
Nya requested all the background sections for text be changed to white rather than the yellow. 
On careers page: font for each job title seems a little small.

Learn page: please implement more design into the UI.  perhaps a sidebar?
the image for healthy kelp (second parallax image) is not loading, improper image name. 
None of the images on this page are parallax. Please take a look into the styling for this page as well.

**Comment by ohkwon** [comment]
Also, Our Process, Learn, and careers uses styling classes specifically for behavior design. can you make unique classes for each page? (ie. the behavior_design-parallax css class)

**Comment by andrealiz** [comment]
Please fix conflict. Also feedback on the learn page: Center text and Why Behavior button. Change the four phases button design or remove the button in general and make the "Learn.." into a link. Same thing for the 10 Behavior Building Blocks. Change headers from parallax to sub-headers, fix wrapper around page and images.

**Comment by andrealiz** [comment]
Looks good!

**Pull request merged**
